# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker images'
- task: ECRPullImage@1
  inputs:
    awsCredentials: 'Default'
    regionName: 'us-west-2'
    repository: 'ecr-push-test'
    imageSource: 'imagetag'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker images'
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'Default'
    regionName: 'us-west-2'
    imageSource: 'imagename'
    sourceImageName: '775382094018.dkr.ecr.us-west-2.amazonaws.com/ecr-push-test'
    repositoryName: 'ecr-push-test'
    removeDockerImage: true